version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      # Mount AI assistant credentials (if authenticated on host)
      - ~/.claude:/home/vscode/.claude:ro
      - ~/.codex:/home/vscode/.codex:ro
    environment:
      # Optional: Use API keys instead of OAuth
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "8000:8000"
    working_dir: /workspace
    command: sleep infinity